### ISSUE TITLE
Add wiki for services

### ISSUE THREAD

**Issue by brantje** [chatnhook/chatnhook#2]
Adding services:   
- [x] Github
- [x] Bitbucket
- [x] Docker
- [ ] Pagerduty
- [x] Patreon
- [x] Scrutinizer
- [x] Codacy
- [x] Slack
- [x] Travis
- [x] CircleCI
- [ ] Telegram 

- [ ] Adding telegram commands

**Comment by maestroi** [comment]
Zabbix integration would be nice.

**Comment by brantje** [comment]
Doc's are moving to readthedocs. Source code can be found at https://github.com/chatnhook/docs
