### ISSUE TITLE
New commands

### ISSUE THREAD

**Issue by brantje** [chatnhook/chatnhook#9]
Would be nice to have the following commands
- /spam -> marks & delete message as spam
- /ban -> ban user from chat

**Comment by redeze** [comment]
mod/admin commands
/whitelist [domain] -> allows links to the website
/unwhitelist [domain] -> opposite of whitelist
/mute [user/reply/id] [time in hours] -> make the bot delete all messages from the user for a certain period of time, maybe message the user privately that he is muted

user commands, if private commands are possible
/rules -> bot privately sends the channel rules
/admin [message] -> sends this message to all admins

**Comment by brantje** [comment]
Closing, moving to https://github.com/chatnhook/commands
